# 1 on /FollowingDirection is right line following, 0 in state is line following
/**:
    ros__parameters:
        /FollowingDirection:        0   # 1  is right, 0 is left
        /InitialHeading:            -1.937315469713706  # set before build
        /LineSpeed:                 33.0
        /ObjectSpeed:               33.0
        /GpsSpeed:                  25.0
        /UseYellow:                 True

/fsm:
    ros__parameters:
        /TimerRate:                 0.05  # rate at which to check and do state specified behavior
        /StartState:                0

/rplidar_node:
    ros__parameters:
        serial_port:                '/dev/LIDAR_PORT'

/lines:
    ros__parameters:
        /LineDetectCropTop:         0.0         # fraction to remove
        /LineDetectCropBottom:      .2
        /LineDetectCropSide:        .2
        /LineDetectDistance:        1.0
        /Debug:                     True


/obstacles:
    ros__parameters:
        /LIDARTrimMin:              1.31  # radians
        /LIDARTrimMax:              4.97  # radians
        /ObstacleFOV:               0.61  # radians
        /PotholeDetectCropTop:      0.0
        /PotholeDetectCropBottom:   0.2
        /PotholeDetectCropSide:     0.2
        /PotholeBufferSize:         5
        /ObstacleDetectDistance:    1.5  # meters
        /Debug:                     False

/gps:
    ros__parameters:
        /WaypointLat1:              39.44818940
        /WaypointLon1:              -83.4882465
        /WaypointLat2:              0.0
        /WaypointLon2:              0.0
        /WaypointLat3:              0.0
        /WaypointLon3:              0.0
        /WaypointLat4:              0.0
        /WaypointLon4:              0.0
        /GPSFollowGoal:             1.5
        /LineToGPSTrans:            5.0
        /Port:                      '/dev/GPS_PORT'
        /Debug:                     False

/teensy:
    ros__parameters:
        /TeensyEncodersPort:        '/dev/TEENSY_PORT'
        /TeensyBaudrate:            115200
        /TeensyUpdateDelay:         .2
        /LineDist:                  0.30
        /SideObjectDist:            1.0
        /BoostIncrease:             2
        /BoostCountThreshold:       20
        /LineBoostMargin:           30.0
        /GPSBoostMargin:            0.1745
        /Debug:                     True

/fusion:
    ros__parameters:
        /EncoderWeight:             .75
        /ExitAngle:                 0.4  # radians
        /Debug:                     True
