# 1 on /FollowingDirection is right line following, 0 in state is line following
/**:
    ros__parameters:
        /RealCourse:                True
        /FollowingDirection:        0           # 1  is right, 0 is left
        /UseYellow:                 False
        /InitialHeading:            188.0       # set before build to degrees!!
        /NorthPointFirst:           False
        /GpsExitHeading:            0.820304     # N, R: -2.321286; N, L: 2.5656318; S, R: -0.575958; S, L: 0.820304
        /CrossRampInGps:            True
        /LineDist:                  0.25
        /EncoderWeight:             .6

/fsm:
    ros__parameters:
        /TimerRate:                 0.05  # rate at which to check and do state specified behavior
        /StartState:                0
        /TurnSpeed:                 20
        /SlightTurn:                20
        /ExitAngle:                 0.3

/rplidar_node:
    ros__parameters:
        serial_port:                '/dev/LIDAR_PORT'

/lines:
    ros__parameters:
        /LineDetectCropTop:         0.0         # fraction to remove
        /LineDetectCropBottom:      .2
        /LineDetectCropSide:        .2
        /LineDetectDistance:        1.0
        /Debug:                     True


/obstacles:
    ros__parameters:
        /LIDARTrimMin:              1.31  # radians
        /LIDARTrimMax:              4.97  # radians
        /ObstacleFOV:               0.61  # radians
        /PotholeDetectCropTop:      0.0
        /PotholeDetectCropBottom:   0.2
        /PotholeDetectCropSide:     0.2
        /PotholeBufferSize:         5
        /ObstacleDetectDistance:    1.35  # meters
        /Debug:                     False

# enter waypoints north to south in converted to dd.mmmmmmm form
/gps:
    ros__parameters:

#        /PracticeWaypointLat1:     42.40094919999999   # tent
#        /PracticeWaypointLon1:     -83.1307195
        /PracticeWaypointLat1:      42.4009412          # our north practice point
        /PracticeWaypointLon1:      -83.13108260000001

        /PracticeWaypointLat2:      42.4008838        # middle north practice
        /PracticeWaypointLon2:      -83.1310741
        /PracticeWaypointLat3:      42.4008475        # middle south practice
        /PracticeWaypointLon3:      -83.131072


#        /PracticeWaypointLat2:      42.400776035        # south practice
#        /PracticeWaypointLon2:      -83.13108550000001 #42.4009412-83.13108260000001
        /PracticeWaypointLat4:      42.4007917          # south point from us
        /PracticeWaypointLon4:      -83.1310758

        # their provided north point = 42.400961833333334 + -83.13160418166666j
        # our nearest recorded point = 42.400974399999996-83.1315972
        /WaypointLat1:              42.40096900         # north real -- adjusted about 83 cm north
        /WaypointLon1:              -83.13160418166666

        # actual point on ramp = 42.400875400000004-83.13161829999999 north
        /WaypointLat2:              42.40088038666667          # center north - shifted north slightly
        /WaypointLon2:              -83.131620365               # shift west

        # 42.4008482-83.1316123 OUR RECORDED POINT
        /WaypointLat3:              42.40084398           # center south - shifted south 2 decimeters
        /WaypointLon3:              -83.131618495

        # their provided south point = 42.400756623333336 + -83.131596585j
        /WaypointLat4:              42.400752623333336   # south real -- adjusted about 113 cm south
        /WaypointLon4:              -83.131596585
        /GPSFollowGoal:             1.0
        /LineToGPSTrans:            5.0
        /Port:                      '/dev/GPS_PORT'
        /Debug:                     True

/teensy:
    ros__parameters:
        /TeensyEncodersPort:        '/dev/TEENSY_PORT'
        /TeensyBaudrate:            115200
        /TeensyUpdateDelay:         .1
        /SideObjectDist:            0.85
        /LineSpeed:                 33.0
        /ObjectSpeed:               32.0
        /GpsSpeed:                  27.0
        /BoostIncrease:             2
        /BoostCountThreshold:       20
        /GPSBoostCountThreshold:    10
        /LineBoostMargin:           30.0
        /GPSBoostMargin:            0.1745
        /Debug:                     True

/fusion:
    ros__parameters:
        /ExitAngle:                 0.4  # radians
        /Debug:                     True
