# 1 on /FollowingDirection is right line following, 0 in state is line following
/**:
    ros__parameters:
        /FollowingDirection:        0   # 1  is right, 0 is left

/fsm:
    ros__parameters:
        /DefaultSpeed:              10
        /TimerRate:                 0.05
        /StartState:                0

/rplidar_node:
    ros__parameters:
        serial_port:                '/dev/LIDAR_PORT'

/lines:
    ros__parameters:
        /LineDetectCropTop:         0.0         # fraction to remove
        /LineDetectCropBottom:      .2
        /LineDetectCropSide:        .2
        /UseYellow:                 False
        /Debug:                     True


/obstacles:
    ros__parameters:
        /LIDARTrimMin:              1.31  # radians
        /LIDARTrimMax:              4.97  # radians
        /ObstacleFOV:               0.43633  # radians
        /PotholeDetectCropTop:      0.0
        /PotholeDetectCropBottom:   0.2
        /PotholeDetectCropSide:     0.2
        /PotholeBufferSize:         5
        /ObstacleDetectDistance:    1.0  # meters
        /Debug:                     False

/gps:
    ros__parameters:
        /WaypointLat1:              39.4481695
        /WaypointLon1:              -83.4882655
        /WaypointLat2:              0.0
        /WaypointLon2:              0.0
        /WaypointLat3:              0.0
        /WaypointLon3:              0.0
        /WaypointLat4:              0.0
        /WaypointLon4:              0.0
        /GPSFollowGoal:             1.5
        /LineToGPSTrans:            5.0
        /Port:                      '/dev/GPS_PORT'
        /Debug:                     True

/teensy:
    ros__parameters:
        /TeensyEncodersPort:        '/dev/TEENSY_PORT'
        /TeensyBaudrate:            115200
        /TeensyUpdateDelay:         .05
        /Debug:                     True
        /LineDist:                  0.25
        /SideObjectDist:            0.75
        /DefaultSpeed:              35.0
        /BoostIncrease:             2
        /BoostCountThreshold:       20
        /LineBoostMargin:           30.0
        /GPSBoostMargin:            0.1745

/fusion:
    ros__parameters:
        /InitialHeading:            -1.5
        /EncoderWeight:             .50
        /ExitAngle:                 0.4  # radians
        /Debug:                     False
