# 1 on /FollowingDirection is right line following, 0 in state is line following
/**:
    ros__parameters:
        /RealCourse:                False
        /FollowingDirection:        0   # 1  is right, 0 is left
        /UseYellow:                 False
        /InitialHeading:            143.0  # set before build to degrees!!
        /NorthPointFirst:           True
        /GpsExitHeading:            2.740165     # N, R: -2.49582; N, L: 2.740165; S, R: -0.401425; S, L: 0.64577
        /CrossRampInGps:            True
        /LineDist:                  0.25
        /EncoderWeight:             .6

/fsm:
    ros__parameters:
        /TimerRate:                 0.05  # rate at which to check and do state specified behavior
        /StartState:                0
        /TurnSpeed:                 20
        /SlightTurn:                20
        /ExitAngle:                 0.4

/rplidar_node:
    ros__parameters:
        serial_port:                '/dev/LIDAR_PORT'

/lines:
    ros__parameters:
        /LineDetectCropTop:         0.0         # fraction to remove
        /LineDetectCropBottom:      .2
        /LineDetectCropSide:        .2
        /LineDetectDistance:        0.85
        /Debug:                     True


/obstacles:
    ros__parameters:
        /LIDARTrimMin:              1.31  # radians
        /LIDARTrimMax:              4.97  # radians
        /ObstacleFOV:               0.61  # radians
        /PotholeDetectCropTop:      0.0
        /PotholeDetectCropBottom:   0.2
        /PotholeDetectCropSide:     0.2
        /PotholeBufferSize:         5
        /ObstacleDetectDistance:    1.2  # meters
        /Debug:                     False

# enter waypoints north to south in converted to dd.mmmmmmm form
/gps:
    ros__parameters:

#        /PracticeWaypointLat1:     42.40094919999999   # tent
#        /PracticeWaypointLon1:     -83.1307195
        /PracticeWaypointLat1:      42.4009412          # our north practice point
        /PracticeWaypointLon1:      -83.13108260000001

        /PracticeWaypointLat2:      42.4008838        # middle north practice
        /PracticeWaypointLon2:      -83.1310741
        /PracticeWaypointLat3:      42.4008475        # middle south practice
        /PracticeWaypointLon3:      -83.131072


#        /PracticeWaypointLat2:      42.400776035        # south practice
#        /PracticeWaypointLon2:      -83.13108550000001
        /PracticeWaypointLat4:      42.4007917          # south point from us
        /PracticeWaypointLon4:      -83.1310758

        # their provided north point = 42.400961833333334 + -83.13160418166666j
        # our nearest recorded point = 42.4009776 + -83.1315994j
        /WaypointLat1:              42.40096900         # north real -- adjusted about 83 cm north
        /WaypointLon1:              -83.13160418166666
        /WaypointLat2:              42.40087238666667          # center north
        /WaypointLon2:              -83.131616365
        /WaypointLat3:              42.40084598           # center south
        /WaypointLon3:              -83.131615495
        # their provided south point = 42.400756623333336 + -83.131596585j
        /WaypointLat4:              42.400756623333336   # south real -- adjusted about 73 cm south
        /WaypointLon4:              -83.131596585
        /GPSFollowGoal:             1.5
        /LineToGPSTrans:            5.0
        /Port:                      '/dev/GPS_PORT'
        /Debug:                     True

/teensy:
    ros__parameters:
        /TeensyEncodersPort:        '/dev/TEENSY_PORT'
        /TeensyBaudrate:            115200
        /TeensyUpdateDelay:         .1
        /SideObjectDist:            0.85
        /LineSpeed:                 33.0
        /ObjectSpeed:               32.0
        /GpsSpeed:                  25.0
        /BoostIncrease:             2
        /BoostCountThreshold:       20
        /LineBoostMargin:           30.0
        /GPSBoostMargin:            0.1745
        /Debug:                     True

/fusion:
    ros__parameters:
        /ExitAngle:                 0.4  # radians
        /Debug:                     True
