# 1 on /FollowingDirection is right line following, 0 in state is line following
/**:
    ros__parameters:
        /FollowingDirection:        1   # 1  is right, 0 is left
        /UseYellow:                 False
        /InitialHeading:            264.0  # set before build to degrees!!
        /LineSpeed:                 33.0
        /ObjectSpeed:               33.0
        /GpsSpeed:                  25.0
        /LineDist:                  0.22
        /EncoderWeight:             .6

/fsm:
    ros__parameters:
        /TimerRate:                 0.05  # rate at which to check and do state specified behavior
        /StartState:                0
        /TurnSpeed:                 20
        /SlightTurn:                22
        /ExitAngle:                 0.9

/rplidar_node:
    ros__parameters:
        serial_port:                '/dev/LIDAR_PORT'

/lines:
    ros__parameters:
        /LineDetectCropTop:         0.0         # fraction to remove
        /LineDetectCropBottom:      .2
        /LineDetectCropSide:        .2
        /LineDetectDistance:        1.0
        /Debug:                     True



/obstacles:
    ros__parameters:
        /LIDARTrimMin:              1.31  # radians
        /LIDARTrimMax:              4.97  # radians
        /ObstacleFOV:               0.61  # radians
        /PotholeDetectCropTop:      0.0
        /PotholeDetectCropBottom:   0.2
        /PotholeDetectCropSide:     0.2
        /PotholeBufferSize:         5
        /ObstacleDetectDistance:    1.1  # meters
        /Debug:                     False

/gps:
    ros__parameters:
        /WaypointLat1:              42.400927 # south practice
        /WaypointLon1:              -83.131075
        /WaypointLat2:              42.4008601 # center
        /WaypointLon2:              -83.1310840
        /WaypointLat3:              42.400726 # north practice
        /WaypointLon3:              -83.131063
        /WaypointLat4:              42.4007760
        /WaypointLon4:              -83.1310596
        /GPSFollowGoal:             1.5
        /LineToGPSTrans:            5.0
        /Port:                      '/dev/GPS_PORT'
        /Debug:                     True

/teensy:
    ros__parameters:
        /TeensyEncodersPort:        '/dev/TEENSY_PORT'
        /TeensyBaudrate:            115200
        /TeensyUpdateDelay:         .2
        /SideObjectDist:            0.85
        /BoostIncrease:             2
        /BoostCountThreshold:       20
        /LineBoostMargin:           30.0
        /GPSBoostMargin:            0.1745
        /Debug:                     True

/fusion:
    ros__parameters:
        /ExitAngle:                 0.4  # radians
        /Debug:                     True
